naadvenu_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin-@naadvenu-2018/', admin.site.urls),
    path("", include("pages.urls")),

]

pages/urls.py
from django.urls import path, include, re_path
from pages import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name='home'),
    path("passes", views.passes, name='passes'),
    path('show_data/', views.show_data, name='show_data'),
    path('download_data/', views.download_data, name='download_data'),
    path('scan-qr-code-@08-06-2024/', views.qr_form_view, name='qr_form_view'),
    path('tinymce/', include('tinymce.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/models.py
from django.db import models

class NamostuteQRFormData(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    address = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_QRscanned = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} - {self.phone_number}"

pages/forms.py
from django import forms
from .models import NamostuteQRFormData

class QRForm(forms.ModelForm):
    class Meta:
        model = NamostuteQRFormData
        fields = ['name', 'email', 'phone_number', 'address']

pages/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import QRForm
from .models import NamostuteQRFormData
from django.utils import timezone
import json
from django.http import HttpResponse
import csv


def home(request):
    #return render(request, "pages/namostute-pass.html", {})
    return render(request, "pages/thankyou-page.html", {})

def passes(request):
    return render(request, "pages/namostute-pass.html", {})
    #return render(request, "pages/thankyou-page.html", {})
    

def qr_form_view(request):
    if request.method == 'POST':
        form = QRForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            qr_data = NamostuteQRFormData.objects.filter(
                name=data['name'],
                email=data['email'],
                phone_number=data['phone_number'],
                address=data['address']
            ).first()

            if qr_data:
                if qr_data.is_QRscanned:
                    messages.error(request, 'This QR code has already been used.')
                    return redirect('qr_form_view')
                else:
                    qr_data.is_QRscanned = True
                    qr_data.save()
                    messages.success(request, 'QR code scanned successfully!')
                    return redirect('qr_form_view')
            else:
                NamostuteQRFormData.objects.create(
                    name=data['name'],
                    email=data['email'],
                    phone_number=data['phone_number'],
                    address=data['address'],
                    created_at=timezone.now(),
                    is_QRscanned=True
                )
                messages.success(request, 'Form submitted successfully!')
                return redirect('qr_form_view')
        else:
            messages.error(request, 'Form submission failed. Please correct the errors and try again.')
    else:
        form = QRForm()
    return render(request, 'pages/qr-form.html', {'form': form})

def show_data(request):
    data = NamostuteQRFormData.objects.all()
    return render(request, 'pages/show_data.html', {'data': data})

def download_data(request):
    data = NamostuteQRFormData.objects.all()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="qr_data.csv"'

    writer = csv.writer(response)
    writer.writerow(['Name', 'Email', 'Phone Number', 'Address', 'Created At'])
    for item in data:
        writer.writerow([item.name, item.email, item.phone_number, item.address, item.created_at])

    return response

pages/templates/pages/qr-form.html
{% extends "base.html" %} {% load static %} {% block title %}Namostute 2024 - Naadvenu{% endblock title %} {% block page_content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/html5-qrcode/2.3.8/html5-qrcode.min.js" integrity="sha512-r6rDA7W6ZeQhvl8S7yRVQUKVHdexq+GAlNkNNqVC7YyIV+NwqCTJe2hDWCiffTyRNOeGEzRRJ9ifvRm/HCzGYg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<style>
    .qr-container {
        background-color: #f8f8ff;
        padding: 2rem;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        max-width: 600px;
        width: 100%;
        margin: auto;
        height: 100vh;
    }
    
    h1 {
        text-align: center;
        margin-bottom: 2rem;
    }
    
    .qr-reader {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    
    .buttons {
        display: flex;
        justify-content: center;
        gap: 1rem;
        margin-bottom: 1rem;
    }
    
    .btn {
        background-color: #010316;
        color: #f8f8ff;
        border: 1px solid #010316;
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }
    
    .btn:hover {
        border: 1px solid #010316;
    }
    
    .form {
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }
    
    .input {
        padding: 0.5rem 1rem;
        border: 1px solid #ccc;
        border-radius: 0.5rem;
        font-size: 1rem;
    }
    
    .textarea {
        resize: vertical;
    }
    
    .submit {
        background-color: #010316;
        color: #f8f8ff;
        border: none;
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }
    
    .submit:hover {
        border: 1px solid #010316;
    }
    
    #reader video {
        width: auto;
        height: auto;
        display: block;
        position: relative;
        border-radius: 10px;
        border: 5px solid #000;
        padding: 10px;
    }
</style>
<div class="qr-container">
    <h1>QR Code Scanner</h1>

    <div class="qr-reader">
        <div class="buttons"> <button id="start-camera-scan-btn" class="btn">Scan from Camera</button> <button id="upload-image-btn" class="btn">Upload from Gallery</button> <button id="stop-scan-btn" class="btn" style="display: none;">Stop Scanning</button> </div>
        <div id="reader" style="width: 300px; height: auto; margin-bottom: 30px; display: none;"></div>
    </div>

    <form method="POST" id="qr-form" class="form">
        {% csrf_token %}
        <input type="text" id="id_name" name="name" placeholder="Name" class="input" />
        <input type="email" id="id_email" name="email" placeholder="Email" class="input" />
        <input type="tel" id="id_phone_number" name="phone_number" placeholder="Phone Number" class="input" />
        <textarea id="id_address" name="address" placeholder="Address" class="input textarea"></textarea>
        <button type="submit" class="btn submit">Submit</button>
    </form>
    <div id="message-container">
        {% if messages %}
        <div class="messages mt-3">
            {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

<script>
    let html5QrCode;

    function startScanning() {
        html5QrCode = new Html5Qrcode("reader");
        html5QrCode.start({
                facingMode: "environment"
            }, {
                fps: 10,
                qrbox: 250
            },
            (decodedText) => {
                try {
                    const data = JSON.parse(decodeURIComponent(decodedText));
                    document.getElementById('id_name').value = data.name;
                    document.getElementById('id_email').value = data.email;
                    document.getElementById('id_phone_number').value = data.phone;
                    document.getElementById('id_address').value = data.location;
                    stopScanning();
                } catch (e) {
                    console.error('Error parsing JSON from QR code:', e);
                }
            },
            (errorMessage) => {
                console.error('QR code scanning error:', errorMessage);
            }
        ).catch((err) => {
            console.error('Error starting QR code scanner:', err);
        });
        document.getElementById('reader').style.display = 'block';
        document.getElementById('stop-scan-btn').style.display = 'inline-block';
    }

    function stopScanning() {
        if (html5QrCode) {
            html5QrCode.stop().then(() => {
                html5QrCode.clear();
                document.getElementById('reader').style.display = 'none';
                document.getElementById('stop-scan-btn').style.display = 'none';
            }).catch((err) => {
                console.error('Error stopping QR code scanner:', err);
            });
        }
    }

    document.getElementById('start-camera-scan-btn').addEventListener('click', startScanning);
    document.getElementById('stop-scan-btn').addEventListener('click', stopScanning);

    document.getElementById('upload-image-btn').addEventListener('click', function() {
        const input = document.createElement('input');
        input.type = 'file';
        input.accept = 'image/*';
        input.addEventListener('change', function(event) {
            const file = event.target.files[0];
            if (file) {
                html5QrCode = new Html5Qrcode("reader");
                html5QrCode.scanFile(file, true)
                    .then(decodedText => {
                        try {
                            const data = JSON.parse(decodeURIComponent(decodedText));
                            document.getElementById('id_name').value = data.name;
                            document.getElementById('id_email').value = data.email;
                            document.getElementById('id_phone_number').value = data.phone;
                            document.getElementById('id_address').value = data.location;
                            document.getElementById('submit-btn').click();
                        } catch (e) {
                            console.error('Error parsing JSON from QR code:', e);
                        }
                    })
                    .catch(err => {
                        console.error('Error scanning QR code from file:', err);
                    });
            }
        });
        input.click();
    });

    document.addEventListener('DOMContentLoaded', function() {
        const messagesContainer = document.getElementById('message-container');
        if (messagesContainer) {
            const messages = messagesContainer.querySelectorAll('.messages .success');
            if (messages.length > 0) {
                alert(messages[0].innerText);
            }
        }
    });
</script>

{% endblock page_content %}

pages/templates/pages/show_data.html
{% extends "base.html" %} {% load static %} {% block title %}Namostute 2024 - Naadvenu{% endblock title %} {% block page_content %}

<h1>QR Form Data</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Address</th>
    </tr>
    {% for item in data %}
    <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.email }}</td>
        <td>{{ item.phone_number }}</td>
        <td>{{ item.address }}</td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'download_data' %}">Download Data</a> {% endblock page_content %}

pages/templates/pages/thankyou-page.html
{% extends "base.html" %} {% load static %} {% block title %}Namostute 2024 - Naadvenu{% endblock title %} {% block page_content %}
<style>
    @import url('https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900&display=swap');
    html,
    body {
        font-family: 'Raleway', sans-serif;
    }
    .thankyou-page ._header {
        background: #0a4c30;
        text-align: center;
        padding: 50px 30px;
        background: #0a4c30 url(https://codexcourier.com/images/main_page.jpg) center/cover no-repeat;
    }
    
    .thankyou-page ._header .logo {
        max-width: 200px;
        margin: 0 auto 50px;
    }
    
    .thankyou-page ._header .logo img {
        width: 100%;
    }
    
    .thankyou-page ._body {
        margin: -70px 0px 0px 0px;
    }
    
    .thankyou-page ._body ._box {
        margin: auto;
        max-width: 80%;
        padding: 50px;
        background: white;
        border-radius: 3px;
        box-shadow: 0 0 35px rgba(10, 10, 10, 0.12);
        -moz-box-shadow: 0 0 35px rgba(10, 10, 10, 0.12);
        -webkit-box-shadow: 0 0 35px rgba(10, 10, 10, 0.12);
    }
    
    .thankyou-page ._body ._box h2 {
        font-size: 32px;
        font-weight: 600;
        color: #4ab74a;
    }
    
    .thankyou-page ._body ._box p {
        font-size: 18px;
        font-weight: 600;
        color: #010316;
        text-align: center;
    }
</style>
<div class="thankyou-page">
    <div class="_header">
        <div class="logo">
            <img src="{% static 'images/namostute.png' %}" alt="Naadvenu">
        </div>
    </div>
    <div class="_body">
        <div class="_box">
            <h2>
                <strong>We Are Housefull!</strong> We look forward to seeing you all on June 8th at 5:30 PM for a great evening filled with joy.
            </h2>
            <p>
                Thank you so much for registering for Namostute. We truly appreciate you taking the time to fill out the form. It means a lot to us, just like you do! Thanks for being you.
            </p>
        </div>
    </div>
</div>

{% endblock page_content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Naadvenu Flute Classes">
    <meta name="keywords" content="Naadvenu, Namostute, Flute, Music, Classical, Airoli, Thane, Navi Mumbai, Harmonium, Flute Classes, Akash Surywanshi">
    <meta name="author" content="Naadvenu">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <title>{% block title %}Naadvenu{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <style>
         @media only screen and (max-width: 991px) {
     .main-content {
     height: auto !important;
 }
 }
    </style>
</head>

<body>
    <div id="main">
        
        <div class="main-content">
            <div class="">{% block page_content %}{% endblock page_content %}</div>
        </div>

        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="copyright">
                            <p>© Copyright 2024 <a href="">Naadvenu</a> I All Rights Reserved</p>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="footer-social">
                            <ul>
                                <li><a href="javascript:void(0)"><i class="fa-brands fa-youtube"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="fa-brands fa-facebook"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="fa-brands fa-square-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>

</html>